### ISSUE TITLE
(not-set) in google analytics when sending events from server side?

### ISSUE THREAD

**Issue by cqcn1991** [railslove/rack-tracker#106]
I track some event server side using rack-tracker

However, when I view the results in GA, it seems like location, browser info are all not set when sending from server-side. 

I want to know, how can I fill this information? I think this info can all get from cookies and then sent to GA from server-side?

**Comment by bumi** [comment]
this is the current google analytics template: https://github.com/railslove/rack-tracker/blob/master/lib/rack/tracker/google_analytics/template/google_analytics.erb
You should see there what information is injected. 

if something is missing please open an issue. thanks.
