### ISSUE TITLE
Extend README with a Dynamic Facebook Pixel Options example

### ISSUE THREAD

**Issue by simonknoll** [railslove/rack-tracker#108]
Would it be possible to add an example on how to use the following feature
https://github.com/railslove/rack-tracker/pull/101
I've tried to take advantage of this feature but I keep failing. How should the lambda be passed to the config/initializer?

**Comment by simonknoll** [comment]
I managed to get it working. Thanks. I've created a pull request.

**Comment by bumi** [comment]
awesome, happy to hear that it worked and thanks for the pull request to improve the readme on this. 
I will look at it tomorrow.
