### ISSUE TITLE
Add the functionality to dynamically deactivate tracker injection

### ISSUE THREAD

**Issue by simonknoll** [railslove/rack-tracker#110]
# Feature request
Would it make sense to you to have the possibility to add a lambda option in order to deactivate dynamically the tracker injection?
Something like:
```ruby
  config.middleware.use(Rack::Tracker) do
    handler :facebook_pixel, {id: lambda {|env| env['PIXEL_ID']}, active: lambda {|env| env['PIXEL_ACTIVE']}}
  end
```

**Comment by kofronpi** [comment]
Would also be useful for GPDR compliance when user does not consent. How could we access current_user ?

**Comment by bumi** [comment]
in the latest version rack-tracker respects the Do Not Track HTTP header as described [here](https://github.com/railslove/rack-tracker#respecting-the-do-not-track-dnt-http-header) 

but yes having a bit more flexible option could be interesting. 
This could be done by extending the check [here](https://github.com/railslove/rack-tracker/blob/master/lib/rack/tracker/handler.rb#L43) to call a configuration option. 

pull requests are very welcome. :)

**Comment by kofronpi** [comment]
As per https://github.com/railslove/rack-tracker/issues/146 this seems to be already doable ?

**Comment by luizeof** [comment]
Hey Folks .. @kofronpi @simonknoll ... thanks for your tip @bumi !

To dynamically disable the tracker you can make the following:

```ruby
class ApplicationController < ActionController::Base

    def skip_tracker
        request.env["HTTP_DNT"] = '1'
    end

...
```

On your GDPR / AMP / etc Controller ....

```ruby
class EventsController < ApplicationController

    before_action :skip_tracker

...
````

**Comment by luizeof** [comment]
Also works for #146
