### ISSUE TITLE
1.5.1 patch release with regex fix

### ISSUE THREAD

**Issue by bumi** [railslove/rack-tracker#112]
We must do a 1.5.1 bugfix release with this commit: (already included in 1.6.0)
https://github.com/railslove/rack-tracker/commit/b3d11e65dfc4ff60d7909c449a0e336f4da2ffb5

**Comment by DonSchado** [comment]
I'm not sure if this is really necessary 🤔 

What might be a possible reason to not be able to update to 1.6?

**Comment by bumi** [comment]
because semantic versioning. it is a rather important bug fix and project that specify `~>1.5.0` as a version should get that fix. 

the patch version says it is a backwards-compatible bug fix. 
the minor version introduced new features that are backwards-compatible.

**Comment by DonSchado** [comment]
Alright then, do it! :)

**Comment by bumi** [comment]
thanks!

**Comment by bumi** [comment]
bump, @DonSchado  can you still to do a 1.5.1 release?
