### ISSUE TITLE
No such handler: Facebook pixel (ArgumentError)

### ISSUE THREAD

**Issue by rafaelbpa** [railslove/rack-tracker#122]
Hello.

Anyone here is tracking fine the Facebook pixel? When I put my code on application.rb, I got an  error saying there is no facebook pixel. 

My application.rb:

```
config.middleware.use(Rack::Tracker) do
      handler :google_analytics, { tracker: 'UA-XXXXXXX-Y' } #Google works fine
      handler :facebook_pixel, { id: 'MY_PIXEL_HERE' } # Doesn't work
end
```

StackTrace Error:
/Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-tracker-0.2.6/lib/rack/tracker/handler_delegator.rb:46:in `handler': No such Handler: FacebookPixel (ArgumentError)
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-tracker-0.2.6/lib/rack/tracker/handler_delegator.rb:4:in `handler'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-tracker-0.2.6/lib/rack/tracker.rb:78:in `handler'
	from /Users/rafael/Development/Ruby/Xlung/site/config/application.rb:73:in `block in <class:Application>'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-tracker-0.2.6/lib/rack/tracker.rb:74:in `instance_exec'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-tracker-0.2.6/lib/rack/tracker.rb:74:in `initialize'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-tracker-0.2.6/lib/rack/tracker.rb:25:in `new'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-tracker-0.2.6/lib/rack/tracker.rb:25:in `initialize'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/actionpack-3.2.21/lib/action_dispatch/middleware/stack.rb:43:in `new'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/actionpack-3.2.21/lib/action_dispatch/middleware/stack.rb:43:in `build'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/actionpack-3.2.21/lib/action_dispatch/middleware/stack.rb:113:in `block in build'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/actionpack-3.2.21/lib/action_dispatch/middleware/stack.rb:113:in `each'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/actionpack-3.2.21/lib/action_dispatch/middleware/stack.rb:113:in `inject'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/actionpack-3.2.21/lib/action_dispatch/middleware/stack.rb:113:in `build'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/engine.rb:475:in `app'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/application/finisher.rb:31:in `block in <module:Finisher>'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/rafael/Development/Ruby/Xlung/site/config/environment.rb:10:in `<top (required)>'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /Users/rafael/Development/Ruby/Xlung/site/config.ru:3:in `block in <main>'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from /Users/rafael/Development/Ruby/Xlung/site/config.ru:in `new'
	from /Users/rafael/Development/Ruby/Xlung/site/config.ru:in `<main>'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-1.4.5/lib/rack/builder.rb:40:in `parse_file'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/commands/server.rb:46:in `app'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/rack-1.4.5/lib/rack/server.rb:254:in `start'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/commands/server.rb:70:in `start'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/commands.rb:55:in `block in <top (required)>'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/commands.rb:50:in `tap'
	from /Users/rafael/.rvm/gems/ruby-2.1.5@xlung/gems/railties-3.2.21/lib/rails/commands.rb:50:in `<top (required)>'
	from script/rails:40:in `require'
	from script/rails:40:in `<main>'

PS: if I put :facebook instead of :facebook_pixel the code compile, but does not appear my event on my pixel analytics... 

Any tips?? Am I doing something wrong?

**Comment by DonSchado** [comment]
Hi @rafaelbpa! 
Thanks for reporting this. 
I will check, if that's a bug

**Comment by rafaelbpa** [comment]
Sorry, I'm didn't see we had two versions of rack-tracker on our project, 1.7.0 and a legacy one (0.2.6). Removing the old one fixed the issue.

**Comment by DonSchado** [comment]
Awesome, thanks for reporting back!
