### ISSUE TITLE
Event objects can't be properly serialized using Rails :json serializer

### ISSUE THREAD

**Issue by jhilden** [railslove/rack-tracker#13]
Background:  `Rails.application.config.action_dispatch.cookies_serializer` is set to `:json` (or `:hybrid`)

Problem:  A rack tracker event object (such as `Rack::Tracker::GoogleAnalytics::Send`) wich was stored in the session and retrieved again, will be deserialized as a string like `"#<Rack::Tracker::GoogleAnalytics::Send type=\"event\", category=\"...\", action=\"...\">" `" instead of a proper object.

This results in an exception like `NoMethodError: undefined method 'write' for #<String:0x00000007ae8bf0>`

I'm not sure what the event objects need to implement in order to serialize well to JSON.  Maybe include http://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html ?

**Comment by jhilden** [comment]
As far as I can tell, the JSON serializer in rails 4.1+ simply cannot be used for serializing objects but only for primitves such as hashes, arrays, strings, etc.

So I guess the only possible solution would be to store the events using a hash representation in the session and then reinitialize the original event objects from those hashes.

**Comment by jhilden** [comment]
Fix was merged into master.

**Comment by jhilden** [comment]
This issue has been resolved by PR #16 but when this change is deployed there can be exceptions with old session data that still contain serialized objects instead of the new hashes.

```
NoMethodError: undefined method `except' for #<Rack::Tracker::GoogleAnalytics::Send category=...>

/ruby/2.1.0/bundler/gems/rack-tracker-2f0c5b612141/lib/rack/tracker/handler.rb:16 in "block in events"
```

How should we react to that?  Just put a warning in the changelog?  Build some migration code?

**Comment by jhilden** [comment]
This only happens if a users last request before the deployment was a redirect that stored the rack-tracker event in the session (as a serialized object) and the next request is after the deployment and excepts a serialized hash.  All further requests are not affected.  In our case it produced 2 exceptions after the deployment.

**Comment by kangguru** [comment]
¯\_(ツ)_/¯ 

maybe advise users to change the session secret, so everything is invalidated

**Comment by jhilden** [comment]
wouldn't that be pretty drastic to invalidate thousands of sessions just to prevent 2 exceptions?
