### ISSUE TITLE
Add support for Google Analytics User ID tracking

### ISSUE THREAD

**Issue by jhilden** [railslove/rack-tracker#14]
https://developers.google.com/analytics/devguides/collection/analyticsjs/user-id

The information about the current user_id should be extractable from the current rack session, or?

**Comment by salimhb** [comment]
I'm investigating this. I'll open a PR when I have a suggestion.

**Comment by salimhb** [comment]
https://github.com/railslove/rack-tracker/pull/15

**Comment by jhilden** [comment]
merged into master
