### ISSUE TITLE
Can't get the google analytics part to work

### ISSUE THREAD

**Issue by neslo** [railslove/rack-tracker#23]
I installed the gem and setup the google analytics part as specificed in the readme.

in config/application.rb i have got 

 config.middleware.use(Rack::Tracker) do
      handler :google_analytics, { tracker: "U-XXX-X"}
  end

and when i check the produced script then i get

ga('create', 'U-xxxxxx-X', {"cookieDomain":"auto"});

and not the expected

ga('create', 'U-xxxxxx-X', 'auto');

I am using rack-tracker 0.3.0 and rails 4.1.6 and ruby 2.1.3

Cheers,
Thomas

**Comment by kangguru** [comment]
hej, thats kinda strange ;)

```ruby
config.middleware.use(Rack::Tracker) do
  handler :google_analytics, { tracker: "U-XXX-X"}
end
```

should produce:

```
ruby
ga('create', 'U-xxxxxx-X', {});
```

as there are no options set for the tracker

```ruby
config.middleware.use(Rack::Tracker) do
  handler :google_analytics, { tracker: "U-XXX-X", cookie_domain: 'auto'}
end
```

will yield to

```ruby
ga('create', 'U-xxxxxx-X', {"cookieDomain":"auto"});
```

which is not what you'r expecting but is semantically the same. its not completely covered in the [documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/domains) but you can see that this "style" is being used for "none". 

the debug addon reveals the following:

![idealiver](https://cloud.githubusercontent.com/assets/72447/6037196/109f6d72-ac51-11e4-8279-3d0e5ea237ec.png)

**Comment by neslo** [comment]
Hi Lars,

Thanks for you detailed response and it highlights the "problem" must be me.

I had initially tested out 

   handler :google_analytics, { tracker: "U-XXX-X", cookie_domain: 'auto'}

to try and get it to match 

ga('create', 'U-xxxxxx-X', 'auto');

which the google docs tells me to expect.

So it seems that i must not have cleared out my cache or something like that when I  switched to

handler :google_analytics, { tracker: "U-XXX-X"}

So all is good at your end then.

Thanks,
Thomas

**Comment by kangguru** [comment]
\o/

cool that everything worked out
