### ISSUE TITLE
Append to body instead of head

### ISSUE THREAD

**Issue by namxam** [railslove/rack-tracker#27]
Shouldn't the JS code be appended to the body tag instead of the header?

**Comment by jhilden** [comment]
As a rule of thumb:  yes tracking JS code should be appended to the `<body>`, but there are certain "business-criticial" tracking codes that you might want to include the `<head>` instead to make sure they fire, even if the page was left very quickly by the user or some other javascript was unable to load.  For example the Google Analytics tracking code (which by the way also loads asynchronously, so page loading is not blocked even though it's included in the `<head>`).  Also the ga tracking code has some features like page load tracking, real-time reporting that only work if you put the code in the ´<head>´

**Comment by salimhb** [comment]
you can set the position to your liking, like this: https://github.com/railslove/rack-tracker/blob/master/spec/integration/google_analytics_integration_spec.rb#L22

**Comment by DonSchado** [comment]
could catch. yes each handler has a position setting. 
but we sadly missed to document the feature @salimhb mentioned :)
