### ISSUE TITLE
Will append to <head> in incorrect circumstances

### ISSUE THREAD

**Issue by dskvr** [railslove/rack-tracker#28]
Use Case: Usabilla.com script, includes `<head>` in the javascript. The JS is included before the `</body>`tag, and would be the second `<head>` tag in the document. Rack-tracker misinterprets this as being the actual `<head>`, and then tries to insert the code inside the javascript itself. 

I can only assume the suggested solution would be "write a handler for usabilla" which I intend to do, however, this is something important to consider. I believe rack-tracker requires better validation when it parses `<head>` to remain reliable and consistent.

There are circumstances where `<head>` may appear in a document. For example, on a website that provides code samples or snippets.

I have tested this theory, and indeed, rack-tracker adds the code to my test case.

```
<pre> <head> <!--rack tracker code appears here --> </pre>
```

Easy solution would be to only add rack-tracker code to `<head>:first` 

Note: I have not dug into rack-tracker codebase to see what the problem is, and it's very possible this could be unique to this particular application. I am on the clock, which is why I haven't taken the time to look into it, or test it on a fresh install. Please double check me, or I'll do a test myself when I have some time.

**Comment by DonSchado** [comment]
interesting issue, would really like to see a solution when you've found the time.

**Comment by fabn** [comment]
This is partially fixed by #53 but it only handle the `</head>` case (unless the literal appears in head itself maybe as a comment).

It won't handle the case when tracking code is added to `</body>` and html document contains a literal `</body>`, that would require a different approach.

In any case using `sub!` instead of `gsub!` is definitely an improvement.

**Comment by fabn** [comment]
I think that the only way to [reliably detect](http://stackoverflow.com/a/1732454/518204) head and body tag would be an html parser but I'm afraid that it will add too much overhead to being done in a middleware.

**Comment by DonSchado** [comment]
no, I think your right. Depends on how reliable it needs to be, or if we can get to a state where it's good enough without an impact on performance.

**Comment by DonSchado** [comment]
So I did some benchmarks on this, 
injecting 2 handlers same time, one append head, one append body.

And in fact with something like nokogiri, 
the code is indeed much nicer, 
but will add round about 50ms for a mid sized html dom, compared to `sub!`. 
(this one for example: https://en.wikipedia.org/wiki/Alan_Turing)

I think that's not acceptable for most apps. 
Rack Tracker seems to add alone round about 10ms to a request (same setup...).

If we could come up with a more rubust pattern matcher, 
I think we could avoid most ambiguous matches, 
by still keep a low impact on performance.

**Comment by bumi** [comment]
I guess we have to add a "won't fix" label here. Any solution discussed would have quite some other downsides, so I guess the current implementation is the best we have right now - and works (mostly)
if anybody has some more ideas, please open the issue again! thanks!
