### ISSUE TITLE
Dynamic trackers

### ISSUE THREAD

**Issue by ruuts** [railslove/rack-tracker#34]
Hi,

I really would like to use this GEM.

Only thing is holding me back:
Ability to dynamically load different trackers.
For example: we have a multi tenant app. Every customer of us have their own GA code.
Due to the configuration it seems not really possible (in a decent way) to do this.

Is there an elegant solution for this?

**Comment by kangguru** [comment]
you can use a block as tracker, which will then be evaluated during runtime

````


```

**Comment by kangguru** [comment]
you can use a dynamic GA code like this:

```ruby
config.middleware.use Rack::Tracker do
      handler :google_analytics, {
        tracker: lambda { |env| env['site_ga'] },
      }
```

and set the code in your controller like this

```ruby

before_action do
  env[:site_ga] = "XXX"
end

```

**Comment by kangguru** [comment]
is that decent enough? :)

**Comment by DonSchado** [comment]
pretty similar to this: https://github.com/railslove/rack-tracker/issues/10

we should document this scenario ;)

**Comment by kangguru** [comment]
oh yea thx @DonSchado for giving a link ;) we should definitely document that!

**Comment by ruuts** [comment]
Aha clear. I think than it's still not possible to pass multiple GA id's to the tracker?
Like described in:

```ruby
config.middleware.use(Rack::Tracker) do
  handler :go_squared, {
    trackers: {
      primaryTracker: 'ABCDEFGH',
      secondaryTracker: '1234567',
    }
  }
end
```

I don't see a construct like:
https://github.com/railslove/rack-tracker/blob/master/lib/rack/tracker/go_squared/template/go_squared.erb#L10
in:
https://github.com/railslove/rack-tracker/blob/master/lib/rack/tracker/google_analytics/template/google_analytics.erb

**Comment by kangguru** [comment]
hm, you want to have more than one tracker on a page?

**Comment by ruuts** [comment]
Yeah for example: https://app.bookingexperts.nl/nl/front/search/22:Go-Parcs?currency=EUR
Maybe server side calls like (gabba: https://github.com/hybridgroup/gabba) would better fit our use case.
Or should we extend the analytics script to handle multiple trackers?

**Comment by kangguru** [comment]
yea. i see what you mean, so this is your use case then? 

form what i see every tracker will then get the same events and tracks, correct? i assume this is a valid case then :) it will get hard if we want to send different events to different trackers.

are you interested in making a PR proposal?

**Comment by ruuts** [comment]
Yeah correct.
I'm interested but I first want to figure out the right tool for this issue.
Grabba might be something (looking into it now). If it's not what we want I think I will move to this.
Will let you know.

**Comment by kangguru** [comment]
cool :dancer: 

its some years ago i was using gabba, so i cannot reason about it :)

**Comment by ruuts** [comment]
@kangguru just used a hybrid approach. Gabba for events / transactions. Client-side library for pageviews (to reduce external calls from our server)

Think it fits our use case better:
1. Multi trackers
2. Just ruby code, no javascript
3. Handle event / transaction tracking in the controller which in my opinion is a better place than the views
4. Easier to test

Downside of course:
1. Rack-tracker is way more automatic.

I think rack-tracker will be a good fit for other projects of us so I will definitely use it at some point and hopefully make a contribution.
