### ISSUE TITLE
Google analytics events not working when value is provided?

### ISSUE THREAD

**Issue by sbrocher** [railslove/rack-tracker#38]
Hi,

Thanks for a very handful and useful gem! I think there maybe a bug when a value is provided for a Google Analytics event. If I do something like this:

tracker do |t|
	  	t.google_analytics :send, { type: 'event', category: 'test', action: 'action', label: 'label' }
end	    

then it works fine. But if I add a value to the params hash, the event wont track. I think it may have something to do with that the template seems to render eventValue: theValue (instead of value: theValue).

In my case I don't need a value so I worked-around it by not providing a value...

**Comment by DonSchado** [comment]
Hey, thank you for reporting this issue. But I think I don't fully understand it.
Could you show me a failing spec to reproduce this?

**Comment by salimhb** [comment]
Hey @sbrocher,
`eventValue` is the correct key name according to google's docs. See: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#eventValue
