### ISSUE TITLE
How do I set to NOT use the debug version of google analytics ?

### ISSUE THREAD

**Issue by Ranhiru** [railslove/rack-tracker#52]
I ran it locally and thought that because it's running on development environment, the gem decided to use the debug version of the analytics.js

However even when pushed to production environment, it still requests for the analytics debug js. 

How do I stop this from happening ?

**Comment by jhilden** [comment]
@Ranhiru I believe that you are using the "Google Analytics Tracking Code Debugger" browser extension, which will automatically add the `ga_debug.js` script to the current page.  Could that be the case?

The code in rack-tracker will only add the regular `analytics.js` script, as you can see here:  https://github.com/railslove/rack-tracker/blob/master/lib/rack/tracker/google_analytics/template/google_analytics.erb#L7 

see: https://developers.google.com/analytics/resources/articles/gaTrackingTroubleshooting#usingDebugger

**Comment by Ranhiru** [comment]
Bingo! That was the case. My bad. Apologies.

**Comment by DonSchado** [comment]
:+1:
