### ISSUE TITLE
Google tag manager - dataLayer - array support

### ISSUE THREAD

**Issue by dpflucas** [railslove/rack-tracker#57]
I would to like add an array to the `dataLayer`. I tried with the following code:

``` ruby
t.google_tag_manager :push, name: 'transactionProducts', value: [{ sku: 'DD44', name: 'T-shirt' }, { sku: 'DD66', name: 'Jeans' }]
```

But the output is a regular JSON object, with the ruby array being interpreted as a string:

``` js
dataLayer.push({
  'transactionProducts': '[{"sku"=>"DD44", "name"=>"T-shirt"}, {"sku"=>"DD66", "name"=>"Jeans"}]'
});
```

**Comment by jhilden** [comment]
Hi @dpflucas,  I think this PR #59 should fix your issue.

Beware of the new syntax.  You will need to change your code from `name: 'transactionProducts', value: ...` to just `transactionProducts: ...`

Would be great to get some feedback from you if it works for you.

**Comment by DonSchado** [comment]
thx @jhilden

**Comment by bumi** [comment]
closing this old issue. this feature is already done :)
