### ISSUE TITLE
Any plans to convert FB custom audience & conversion pixels to new single pixel?

### ISSUE THREAD

**Issue by Tongboy** [railslove/rack-tracker#58]
With FB switching from the existing two pixel system to a single pixel system with an EOL sometime in '16 is there any existing work to move the existing facebook tracker handler to the new standard?

Info: https://www.facebook.com/business/help/1686199411616919

If there is interest but nobody working on it yet I'd be happy to put together a pull request - I figured it would be better to ask first in case the question has come up before.

Thank you

**Comment by kangguru** [comment]
hej,

no theres currently nobody working on that topic, so we'd be happy for
any contribution!

thank you! if you encounter any problems, don't hesitate in contacting us.

**Comment by Tongboy** [comment]
It looks like it was a straight forward change and I think it's backwards compatible.

I think the custom_audience option isn't relevant with the change. To me it seems that should be renamed to tracker to match the rest of the handler standards. Would it make more sense to make this a new handler to maintain the existing FB standards since i'm sure others are using it? I just don't want to step on any toes.

```html
<script type="text/javascript">
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','//connect.facebook.net/en_US/fbevents.js');

  fbq('init', '<%= options[:custom_audience] %>');
  fbq('track', "PageView");
</script>
<noscript>
  <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<%= options[:custom_audience] %>&ev=PageView&noscript=1"/>
</noscript>

<% if events.any? %>
  <script type="text/javascript">
    <% events.each do |event| %>
    fbq('track', <%= event.write %>);
    <% end %>
  </script>

  <noscript>
    <% events.each do |event| %>
      <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<%= options[:custom_audience] %>&amp;ev=<%= event.id %>&amp;value=<%= event.value %>&amp;currency=<%= event.currency %>&amp;noscript=1"/>
    <% end %>
  </noscript>
<% end %>

```

**Comment by jolim** [comment]
@Tongboy Do you plan to make a pull request with this feature? I'd love to get this in front of the maintainers to keep things moving. The second half of 2016 is coming up soon. I'm happy to do the grunt work if you're busy.

**Comment by Tongboy** [comment]
@jolim - Unfortunately I do not. we moved away from the multiple tags to google tag manager after discovering some issues with my proposed change above.

By all means - please have at it!

**Comment by adambedford** [comment]
I'm interested in picking this up. @Tongboy What were the issues you ran into?

**Comment by bumi** [comment]
thanks to all the people who worked on this. 
This issue is old and as the feature is done I am closing this issue.
