### ISSUE TITLE
Async?

### ISSUE THREAD

**Issue by fieldform** [railslove/rack-tracker#62]
We have a controller action that will trigger a Google Adwords Conversion.  Unfortunately, it's asynchronous.  How can we go about this and still benefit from using rack-tracker?

**Comment by kangguru** [comment]
@fieldform could you provide more detail? what to you mean with `asynchronous` in your case?

**Comment by fieldform** [comment]
@kangguru Please see this reference.  http://lucybain.com/blog/2014/google-adwords-async/

**Comment by kangguru** [comment]
i think we can make this happen ;) 

actually the adwords code is doing some weird things anyway. I assume that you're using rails + turbolinks?

**Comment by fieldform** [comment]
@kangguru It turns out our implementation needs to trigger the conversion from some client side javascript, which in terms of patterns is pretty different than what rack-tracker offers.  Thank you, but I think I will close this one.
