### ISSUE TITLE
Getting data from Google analytics

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [railslove/rack-tracker#63]
Hello.

I have set analytics for my mobile application which sends track data to GA. According to this gems readme, I can send tracking data to google via my rails application. However, there isn't written anything about retrieving data from GA.

Is it even possible?

**Comment by kangguru** [comment]
no it isn't. 

the scope of `rack-tracker` is to remove the need to handle all the tracking services without messing with partials or helpers directly within the controller

maybe [google-api-client](https://rubygems.org/gems/google-api-client) is something that you're looking for.
