### ISSUE TITLE
Tracking with params

### ISSUE THREAD

**Issue by jbhatab** [railslove/rack-tracker#64]
I am trying to pass parameters in with my event tracking but it's not working as expected. I was following this, https://github.com/railslove/rack-tracker#parameters. Also I want to know how I can set things up so I can look at and filter each parameter associated with the event. I'm assuming these parameters get passed as "custom variables"?

<img width="1079" alt="top_events_-_google_analytics" src="https://cloud.githubusercontent.com/assets/2458718/13203285/748417ba-d87a-11e5-8351-371d599b0d54.png">

Here's the code.
``` ruby
     tracker do |t|
        t.google_analytics :parameter, { category: params[:category] }
        t.google_analytics :parameter, { people: "#{params[:num_people_min]}-#{params[:num_people_max]}" }
        t.google_analytics :parameter, { appt_duration: params[:appt_duration] }
        t.google_analytics :parameter, { location: location.name } if location.present?
        t.google_analytics :parameter, { appt_start_time_s: params[:appt_start_time_s] }
        t.google_analytics :send, type: "event",
                                  category: "Reservation Form",
                                  action: "Buy Appt",
                                  label: formatted_data_for_analytics(p)
      end
```

I also noticed that for some reason events are not triggering every time. I had a few events that didn't fire when they should have. Let me know if there's common gotchas I'm missing.

**Comment by DonSchado** [comment]
hm weird. thanks for reporting this! 

Maybe we have a bug here, I'm not sure. 
It also seems like we could improve on the specs here: [google_analytics_spec.rb#L176](https://github.com/railslove/rack-tracker/blob/c277b5dd6b94767cd341e2f28e89181c881cd5b7/spec/handler/google_analytics_spec.rb#L176
)

But it's the first time I hear, that there are missing events.

**Comment by jbhatab** [comment]
@DonSchado do you know where the parameters should be showing up? Is it in the 'custom variable' section?

**Comment by jhilden** [comment]
What you are setting with `ga('set', ...)` is the GA feature that used to be called "custom variables".  Nowadays (in `analytics.js`) it is called "custom dimensions and metrics" so it is possible that it appears in a different place in the GA dashboard.  Unfortunately I don't have any recent experience with this feature.

Here is the relevant documentation:  https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets

**Comment by jbhatab** [comment]
Thanks for the response. You can close this. I need to switch over to the new analytics library basically.
