### ISSUE TITLE
How to skip rendering on a view or controller

### ISSUE THREAD

**Issue by fieldform** [railslove/rack-tracker#65]
What if I don't want Google Analytics to be loaded on a view?

**Comment by holden** [comment]
We're having the same issue, we trying to skip rendering on certain controllers or layouts entirely.  Not sure how to best accomplish this?

**Comment by smadeja** [comment]
You can comment it out using this trick:

```erb
<body>
  <%= yield %>

  <!-- fake tag to fool Rack::Tracker
    </body>
  -->
</body>
```

Rack::Tracker will find the fake `</body>` tag and insert its stuff inside the comment. ;-)

**Comment by DonSchado** [comment]
you could "configure" this in a proc by checking the `env["PATH_INFO"]` for your views url.
sorry, this feature is a little bit _hidden_ in the documentation...

You can find an example here: https://github.com/railslove/rack-tracker/issues/34#issuecomment-87623560

**Comment by bumi** [comment]
does @DonSchado's solution work for you? 
If so this might be something that should be documented in the readme?

**Comment by luizeof** [comment]
> You can comment it out using this trick:
> 
> ```
> <body>
>   <%= yield %>
> 
>   
> </body>
> ```
> 
> Rack::Tracker will find the fake `</body>` tag and insert its stuff inside the comment. ;-)

it works! Thanks
