### ISSUE TITLE
Can I use Rack::Tracker middleware both on my host application and my mountable engine ?

### ISSUE THREAD

**Issue by antoniosb** [railslove/rack-tracker#66]
I have an application with an isolated engine mounted. 
I'm trying to insert **Rack::Tracker** middleware on both my host application and my engine, both using the Google Analytics handler.

But I want the engine and the host application to use a different handler. I'm trying to achieve it like:

on _config/application.rb_:

``` Ruby
config.middleware.use('Rack::Tracker') do
      handler :google_analytics, { tracker: 'UA-123222-2' }
end
```

and at _engines/my_engine/lib/my_engine/engine.rb_:

``` Ruby
    initializer "professor.add_middleware" do |app|
      config.app_middleware.use('Rack::Tracker') do
        handler :google_analytics, { tracker: 'UA-0983333-3' }
      end
    end
```

But as I do that, when I go to any page on either my host application or my engine, I see that the both scripts are added to the page, not just the specific one I need. 

i.e.:

``` HTML
<script type="text/javascript">
  if(typeof ga === 'undefined') {
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-0983333-3', {});
  }
  ga('send', 'pageview', window.location.pathname + window.location.search);
</script>
<script type="text/javascript">
  if(typeof ga === 'undefined') {
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-123222-2', {});
  }
  ga('send', 'pageview', window.location.pathname + window.location.search);
</script>
```

this snippet occurs either on **myhostapplication.com/home** or **myengine/home**. And I wanted that only the snippet defined on the engine initializer loads with the engine pages, and the snippet defined on the application loads with the application pages. 

Does anyone knows how can I accomplish that? What I am doing wrong?

**Comment by kangguru** [comment]
interesting case :) actually i'd have expected that the middleware is just mounted once.

I think the easiest would be to set your tracker dynamic based on the context of the request. although that would make your engine kinds dependent on the main app... which you might not wan't :)

It would work like this: https://github.com/railslove/rack-tracker/issues/34#issuecomment-87623560

Configure the middle ware to read the tracker from the request env:

```ruby
config.middleware.use Rack::Tracker do
      handler :google_analytics, {
        tracker: lambda { |env| env['site_ga'] },
      }
end
```

and set it in you main app:

```ruby
before_action do
  env[:site_ga] = "UA-0983333-3"
end
```

and within the engine

```ruby
before_action do
  env[:site_ga] = "UA-123222-2"
end
```

does this suit your needs?

**Comment by antoniosb** [comment]
Despite the fact that I'll have to include it on every base controller I'm implementing, it seems to be working =)

I'll proceed with the configuration, thank you very much!
