### ISSUE TITLE
dateLayer.push data gets duplicated

### ISSUE THREAD

**Issue by StanBoyet** [railslove/rack-tracker#67]
In my registrations controller, if have a simple 

``` ruby
 tracker do |t|
    t.google_tag_manager :push, {
        event:'eventName',
        eventContent:'signup'
    }
end
```

However, the generated code in my HTML ends up being : 

``` javascript
dataLayer.push(
    {"event":"eventName","eventContent":"signup"},
    {"event":"eventName","eventContent":"signup"}
);
```

So I get 2 events fired up, instead of one. I debugged it in controller, with an iterator, with the debug mode of my IDE ... The generating code doesn't seem to be called twice. Would there be a way to check the content of the hash beforehand ? Therefore not pushing the data inside if it's already there. That would be kind of an ugly fix though :)

Let me know if I can be of assistance ! Thanks

**Comment by StanBoyet** [comment]
Well. I submitted the issue too fast ! 

It seems that when I removed the 
````
  config.middleware.use(Rack::Tracker) do
    handler :google_analytics, { tracker: ENV['GOOGLE_ANALYTICS'] }
  end
````

the generated code is not duplicated anymore.

Thanks for this awesome gem. But this might need some clarification in the docs, right ? If so, I'll do the PR, but I don't know if that's the only case it might happen.

**Comment by kangguru** [comment]
@StanBoyet i'm trying to reproduce this behaviour but i'm not having any luck. also in conjunction with turbolinks (which was often causing trouble). i'm closing this for good, if you're still having problems please just open another issue! 

thank you!!! 💚
