### ISSUE TITLE
No way of tracking virtual page views

### ISSUE THREAD

**Issue by PamMarie** [railslove/rack-tracker#70]
This gem is pretty great, but it doesn't seem to have a way to set the page value to a virtual page and check refreshing js. Is this something in the pipes, or simply beyond the intended scope of the gem?

**Comment by DonSchado** [comment]
hm... I'm not sure if that's in the scope of this gem, as the tracking snippets are always server rendered. 
Can you give me an example how you want to use it in your case?

**Comment by bumi** [comment]
Is this still interesting and a feature that should be added to this gem? If so, some more information on how it should work would be great! 

I am closing this issue for now, but please feel free to open it again.
Thanks!
