### ISSUE TITLE
Google Tag Manager validation fails

### ISSUE THREAD

**Issue by rvasquez-flip4new** [railslove/rack-tracker#80]
Hello,

we are using rack-tracker v1.1.0 and we are having problems validating our site. Google says it can't verify the site becouse it is missing the google analytics snippet in the <head> section.

A look at the google documentation confirms that one part of the gtm intergration has to be in the <head> tag and the other one after the opening of the <body> tag.

https://developers.google.com/tag-manager/quickstart

rack-tracker renders both parts before the closing of the body tag. Is there any way to change this?

Thanks in advance!

Best regards
Roberto

**Comment by bumi** [comment]
done in: https://github.com/railslove/rack-tracker/pull/84
