### ISSUE TITLE
exact_position branch is no more

### ISSUE THREAD

**Issue by Fabs** [railslove/rack-tracker#85]
Hello Guys,

Thanks for the nice work :). I am maintaining an application who depended on this.
```ruby
gem "rack-tracker", git:    "https://github.com/railslove/rack-tracker",
                    branch: "exact_position"
```

Looks like the branch is gone, and I can't tell weather this "exact_position" extra functionality got inside the current releases.

is it possible that I will be good by just moving to the stable release of the gem?
```ruby
gem "rack-tracker"
```

**Comment by bumi** [comment]
hey, thanks for reporting this!
I have restored the exact_position branch for you: https://github.com/railslove/rack-tracker/tree/exact_position  but you should move away from the branch and use the official released version as we can not guarantee the availability of branches (and at some point it will be gone again) 

The feature that was worked in that branch on did NOT yet make it into any release. It is adding quite some complexity and we actually questioned the usefulness of the feature. So thanks a lot for reporting that you relying on it! 

Why do you need to specify the "exact position" of the tracker code? Which tracker do you want to be where in your DOM? 
Would be helpful to understand the requirements a bit better... could share your thoughts and what you're trying to do?

**Comment by Fabs** [comment]
Thanks very much for restoring the branch :). 

To be honest I am not sure how we use rack-tracker, is a 2015 dependency and the developer who added is no longer working with us. It looks to me that we actually do not use the exact_position functionality anymore. 

Thanks for the advice on switching to the official release. We plan to fix this dependency on this branch on our end this week.

**Comment by bumi** [comment]
ok, great. thanks for the information!

We also thought that having the configuration option for `head` or `body` should be enough. In many cases the pixel actually has to be at the position defined by the publisher so configuring is not recommended. 
And if somebody needs a more configurable handler a custom handler could be easily written.

Let me know if there is anything else we can help.
