### ISSUE TITLE
Disable tracker from controller

### ISSUE THREAD

**Issue by vilius** [railslove/rack-tracker#87]
Hi, looked through code and it seems there's no way to disable tracker from specific controller action? If that's the current case what would be the cleanest way to implement it?

**Comment by bumi** [comment]
@DonSchado maybe you can help?

**Comment by DonSchado** [comment]
you could "configure" this in a proc.

sorry, that this feature (or maybe workaround?) is still not documented

you can find examples in these issues:
- https://github.com/railslove/rack-tracker/issues/34
- https://github.com/railslove/rack-tracker/issues/10

**Comment by bumi** [comment]
hope this helped? closing this issue for now. 
any recommendations or a PR with documentation for this would be welcome.
