### ISSUE TITLE
facebook pixel fired outside concerned views

### ISSUE THREAD

**Issue by rubyrailsninja** [railslove/rack-tracker#89]
Hi,

first at all, thanks for your great work !

I have installed the tracker and I have few comments.
 
When specified in the controller method :
    tracker do |t|
      t.facebook_pixel :track, { type: 'ViewContent', options: { p: 'my_way' } }
    end
the facebook pixel is correctly fired ..

but there is another one pixel fired too , PageView, altough I have modifyed the facebook_pixel template and delete the js track call in the template.

I still have fbq('track',"PageView"); at the end of the script.

how to avoid having pageview fb pixel on pages whereas nothing about it in the controller method ?

Regards,

**Comment by DonSchado** [comment]
Hey! Thanks for the comment :)

So the pixel is indeed inserted always. 

We have some functionality for google that enables you to check for a proc that helps you decide where to show the script: 
- https://github.com/railslove/rack-tracker/blob/master/lib/rack/tracker/google_analytics/google_analytics.rb#L56
- https://github.com/railslove/rack-tracker/blob/master/lib/rack/tracker/google_analytics/template/google_analytics.erb#L2

We could come up with the same for facebook, 
or something similar which would be more usable for all tracking handlers...

**Comment by rubyrailsninja** [comment]
Hi ! 
thanks for your quick reply
I will take a look on the solution, thanks

and thanks again for your great work ! :+1: 

Keep on ! :)

**Comment by bumi** [comment]
@rubyrailsninja did you get this to work?

**Comment by rubyrailsninja** [comment]
I finally keep all fired pixels, simple et easy solution :D

**Comment by bumi** [comment]
ok, that means it works? can we close this issue?

**Comment by rubyrailsninja** [comment]
Yes, I close it :)
