### ISSUE TITLE
Sending trackCustom events for Facebook

### ISSUE THREAD

**Issue by marisveide** [railslove/rack-tracker#92]
Facebook requirements state that to fire events that are non-standard events, should be fired with trackCustom method.
I see that there is a hard-coded 'track' method, regardless of what is set here:
```ruby
tracker.facebook_pixel :track, {...}
```

If I call it like this:
```ruby
tracker.facebook_pixel :trackCustom, {...}
```
it will anyway send `fbq("track", ...)`.

What's your suggestion, how to send custom events?
Can you fix that, or I am using it wrong?

Thanks!

**Comment by DonSchado** [comment]
Hi @marisveide 

sorry, the name is a bit confusing here. `track` is the name of the event. not the method used by the handler. so we might need a new event class for handling the "custom event". 

If you look at the `google_analytics` or `zanox` handler you see that there are corresponding classes for the symbol you pass to the handler. 

`tracker.handler_name :event_name, {} `

let me know if you need more help on this

**Comment by marisveide** [comment]
Thanks for the answer.
So, how do I call facebook_pixel method to make the JacaScript call the `fbq("trackCustom", ...)`?

**Comment by marisveide** [comment]
I am looking at the file `rack/tracker/facebook_pixel/template/facebook_pixel.erb`:
```ruby
<script type="text/javascript">
  if (typeof fbq == 'undefined') {

    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
    n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
    document,'script','//connect.facebook.net/en_US/fbevents.js');

    fbq('init', '<%= options[:id] %>');
    fbq('track', "PageView");
  }
</script>
<noscript>
  <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<%= options[:id] %>&ev=PageView&noscript=1"/>
</noscript>

<% if events.any? %>
  <script type="text/javascript">
    <% events.each do |event| %>
      fbq("track", <%= event.write %>);
    <% end %>
  </script>
<% end %>
```

There is no way it could take any other symbol from the `tracker.facebook_pixel :track, {...}` instead of `:track`, because it's clearly hard-coded string in `fbq("track"...)`.

Would you be able to fix that?

**Comment by DonSchado** [comment]
well "fix" is the wrong word here. It simply wasn't implemented before. :)
But I invite you to review https://github.com/railslove/rack-tracker/pull/93 

let me know in the PR if it works like you expect.

cheers

**Comment by marisveide** [comment]
@DonSchado super sorry for calling this a fix. You are right, I meant - add that enhancement.
Reviewed, nice code culture, btw!

**Comment by DonSchado** [comment]
cool, please check the new released version and let me know if there are any issues.
