### ISSUE TITLE
Facebook Pixel doesn't work with Turbolinks

### ISSUE THREAD

**Issue by DanaMarchis** [railslove/rack-tracker#96]
Hello guys!

I have this in my config file 
`config.middleware.use(Rack::Tracker) do
    handler :facebook_pixel, { id: ENV.fetch('PIXEL_ID'), position: :body }
  end`

and this in index action in controller 
`tracker do |t|
     t.facebook_pixel :track, { type: 'ViewContent' }
  end`

I'm using Facebook Pixel Helper and it shows "one pixel found" only if a do a full page reload ( I'm using turbolinks )

**Comment by DonSchado** [comment]
Hey @DanaMarchis have you found a solution you want to share here?

**Comment by DanaMarchis** [comment]
Well, I was using AdBlock and it blocked 'facebook connect' .. so, you have to pause your adblocker :)

**Comment by DonSchado** [comment]
:D alright, thanks for the feedback!
