### ISSUE TITLE
Where to put custom handlers?

### ISSUE THREAD

**Issue by jacobpatton** [railslove/rack-tracker#99]
Thanks for the great gem — I'm using it successfully in production for FB and GA.

I'm trying to add a custom handler for Drip, but I'm having trouble.

By placing your sample code for a generic "MyHandler" into app/middleware, I get this error:

`/app/middleware/templates/my_handler.erb:2:in 'block in singleton class': undefined local variable or method 'options' for MyHandler:Class (NameError)`

I reckon it's a simple mistake. Any idea where I've gone awry?

app/middleware/my_handler.rb looks like:
```
class MyHandler < Rack::Tracker::Handler
  Tilt.new( File.join( File.dirname(__FILE__), 'templates', 'my_handler.erb')).render(self)
end
```

app/middleware/templates/my_handler.erb
```
<script>
  console.log('my tracker: ' + <%= options.to_json %>)
</script>
```

relevant bit from config/development.rb:
```
  config.middleware.use(Rack::Tracker) do
    handler MyHandler, { awesome: true }
  end
```

**Comment by DonSchado** [comment]
Hm... is the `Tilt.new ...` call in it's own `render` method or like in your example on class level? 

Do you have a minimal setup for me where you replicate this problem and I can just checkout the code?

**Comment by jacobpatton** [comment]
Strange: In setting up the demo for you, everything's decided to work now, so I guess we're good here.

Thanks for your help / sorry for wasting your time.

**Comment by DonSchado** [comment]
Cool! Glad it worked out for you 👍  thanks for the feedback! :)

**Comment by DonSchado** [comment]
btw, the drip handler sounds interesting for the project.
So if you like to contribute it when it's done, that would be awesome! :)
